export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const SELLREQUEST_LIST_REQUEST = 'SELLREQUEST_LIST_REQUEST'
export const SELLREQUEST_LIST_SUCCESS = 'SELLREQUEST_LIST_SUCCESS'
export const SELLREQUEST_LIST_FAIL = 'SELLREQUEST_LIST_FAIL'

export const STAT_REQUEST = 'STAT_REQUEST'
export const STAT_SUCCESS = 'STAT_SUCCESS'
export const STAT_FAIL = 'STAT_FAIL'

export const SELLREQUEST_MANAGEMENT_REQUEST = 'SELLREQUEST_MANAGEMENT_REQUEST'
export const SELLREQUEST_MANAGEMENT_SUCCESS = 'SELLREQUEST_MANAGEMENT_SUCCESS'
export const SELLREQUEST_MANAGEMENT_RESET = 'SELLREQUEST_MANAGEMENT_RESET'
export const SELLREQUEST_MANAGEMENT_FAIL = 'SELLREQUEST_MANAGEMENT_FAIL'

